### PR TITLE
Feat/adding people chains

### PR DESCRIPTION
**Pull request by stepanLav**

### CODE REVIEW

**Review by Tbaut — CHANGES_REQUESTED** [review]
(edited)

**Review by Tbaut — COMMENTED** [review]
sorry, I spoke too soon. Only Polkadot seems new here.

**Review by Tbaut — CHANGES_REQUESTED** [review]
Can you please add the Westend People Chain too?

**Review by pgolovkin — APPROVED** [review]

**Comment by stepanLav** [comment]
> Can you please add the Westend People Chain too?

yeah, opened a PR - https://github.com/novasamatech/nova-utils/pull/2945

**Review by Tbaut — APPROVED** [review]
Amazing thanks

**Pull request merged**
